<a href="https://colab.research.google.com/github/habiba-1215/Machine-Learning-Training/blob/main/Copy_of_Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **bold text**### Numpy Assignment

1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.<br>


SOL:  https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php


In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
import numpy as np
np.full(10,5)
#another method

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

2.  Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. <br>
SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-25.php

In [ ]:
import numpy as np
np.arange(10,22).reshape((3, 4))


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

3.  Write a NumPy program to check whether two arrays are equal (element wise) or not.<br>

> Indented block



SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-44.php

In [ ]:
import numpy as np
array1 = ([1,2,3,4])
array2 = ([1,24,7,7])
c = np.in1d(array1,array2)
print(c)


[ True False False False]


*4*.  Write a NumPy program to swap rows and columns of a given array in reverse order. <br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-58.php

In [ ]:
import numpy as np
nums = np.array([[[1, 2, 3, 4],
               [0, 1, 3, 4],
               [90, 91, 93, 94],
               [5, 0, 3, 2]]])
print("Original array:")
print(nums)
print("\nSwap rows and columns of the said array in reverse order:")
new_nums = print(nums[::-1, ::-1])
print(new_nums)
#can you find another method?

Original array:
[[[ 1  2  3  4]
  [ 0  1  3  4]
  [90 91 93 94]
  [ 5  0  3  2]]]

Swap rows and columns of the said array in reverse order:
[[[ 5  0  3  2]
  [90 91 93 94]
  [ 0  1  3  4]
  [ 1  2  3  4]]]
None


5. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.<br>
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-4.php

In [ ]:
import numpy as np
array1 = np.zeros(10)
print("Update sixth value to 11")
array1[6] = 11
print(array1)

Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


6. Write a NumPy program to convert a list and tuple into arrays. <br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-11.php

In [ ]:
import numpy as np
list1 = [1, 2, 3, 4]
print("List to array: ")
print(np.asarray(list1))
tuple1 = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(tuple1))

List to array: 
[1 2 3 4]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


7.  Write a NumPy program to change the dimension of an array. <br>
Expected Output:<br>
6 rows and 0 columns<br>
(6,)<br>
(3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-35.php

In [ ]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6])
print("6 rows and 0 columns")
print(array1.shape)

array2 = np.array([[1, 2, 3],[4, 5, 6],[7,8,9]])
print("(3, 3) -> 3 rows and 3 columns ")
print(array2)

array3 = np.array([1,2,3,4,5,6,7,8,9])
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
array3.shape = (3, 3)
print(array3)

6 rows and 0 columns
(6,)
(3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Write a NumPy program to compute the multiplication of two given matrices.<br>
SOL: https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-1.php

In [ ]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([1, 2, 3, 4, 5, 6])
mul = array1  * array2
print(mul)

[ 1  4  9 16 25 36]


9. Write a NumPy program to create a 3x3x3 array with random values. <br>
Expected Output: <br>
[[[ 0.48941799 0.58722213 0.43453926] <br>
[ 0.94497547 0.81081709 0.1510409 ] <br>
[ 0.66657127 0.29494755 0.48047144]] <br>
[[ 0.02287253 0.95232614 0.32264936] <br>
[ 0.67009741 0.25458304 0.16290913] <br>
[ 0.15520198 0.86826529 0.9679322 ]]  <br>
[[ 0.13503103 0.02042211 0.24683897]  <br>
[ 0.97852158 0.22374748 0.10798856]  <br>
[ 0.62032646 0.5893892 0.16958144]]] <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-3.php

In [1]:
import numpy as np
import random
array1 = np.random.rand((3*3*3))
print(array1)

[0.9770953  0.18056392 0.83008767 0.68421257 0.41220344 0.50052127
 0.13606804 0.46315291 0.75469251 0.25291187 0.57395112 0.47093357
 0.81106273 0.4480144  0.15111598 0.26456751 0.8349391  0.99868149
 0.3777134  0.47683133 0.70914666 0.05957273 0.78632593 0.07572892
 0.00221417 0.29807901 0.20132366]


10. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data. <br>
Expected Output: <br>
Sorted indices: <br>
[4 0 5 3 6 1 2] <br>
Sorted data:  <br>
1682 38.0  <br>
1023 40.0  <br>
5241 40.0  <br>
1671 41.0  <br>
4532 42.0  <br>
5202 42.0  <br>
6230 45.0  <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-4.php

In [4]:
import numpy as np
id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
height = np.array([40, 42, 45, 41, 38, 40, 42])
indices = np.lexsort((id, height))
print("indices: ")
print(indices)
print(" data: ")
for n in indices:
  print(id[n], height[n])

indices: 
[4 0 5 3 6 1 2]
 data: 
1682 38
1023 40
5241 40
1671 41
4532 42
5202 42
6230 45
